version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl:enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # - ./data/esdata:/usr/share/elasticsearch/data # Improve performance
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kib01
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
      # - ./data/kibanadata:/usr/share/kibana/data # Improve performance
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
